### ISSUE TITLE
tunnel -c install error

### ISSUE THREAD

**Issue by freebooterish** [SomajitDey/tunnel#5]
First of all, thank you for sharing the excellent project, When i run:  ./tunnel -c install in Macos (Monterey), it pop-up error:
./tunnel: line 323: conditional binary operator expected
./tunnel: line 323: syntax error near `subcommand'
./tunnel: line 323: `  if [[ -v subcommand ]]; then ${@}; exit "${?}";fi' 

Can you give some tips on how to solve it? Thank you.

**Comment by SomajitDey** [comment]
Dear @freebooterish, extremely sorry for the delayed reply. 

Thanks a lot for reporting this error. However, it stumps me - I guess I'd need to get my hands on a macOS to sort this out. Unfortunately, I only have WSL for now. Would see if I can grab a mac from one of my friends. I am keeping this thread open until I fix this and would write to you here once fixed. Let me know if you come up with a fix in the meantime.

**Comment by ozskywalker** [comment]
The version of bash macOS is using isn't compatible with some of the elements incorporated into the script.  It's not just that line, there's a number of sections at play here, and that would invoke a more extensive re-write just to be compatible enough to run on macOS. 

Would recommend if you have to run on macOS, run it in a ubuntu/alpine linux container with ports exposed to the Host OS.

**Comment by SomajitDey** [comment]
Thanks a lot for your comment, @ozskywalker.  I think now this issue may be closed.
